### ISSUE TITLE
Does not load style of <pwa-auth> component

### ISSUE THREAD

**Issue by Odonno** [nmetulev/wc-react#1]
I tried to use your library to use the new <pwa-auth> component from https://github.com/pwa-builder/pwa-auth

It worked pretty much but some styles does not seem to be loaded. Here is a list of steps to reproduce the behavior:

### Reproduction steps

Install packages in a react app:

```
yarn add @pwabuilder/pwaauth wc-react
```

In a functional component, import and use the component:

```ts
import React from 'react';
import { wrapWc } from 'wc-react';
import '@pwabuilder/pwaauth';

const PwaAuth = wrapWc('pwa-auth');

const Login = (props: any) => {
    return (
        <div>
            <PwaAuth 
                microsoftKey="123456abc"
                googleKey="123456abc"
                facebookKey="123456abc"
                appearance="list"
            />
        </div>
    );
};

export default Login;
```

You will now see the list of login buttons but with no style applied on them...

### Additional infos

I just want to say "No rush!". For the moment, I am using the web component as-is and it works.

**Comment by nmetulev** [comment]
Thanks for the issue @Odonno. 

The difference between using the wrapper and not is that the wrapper sets the property of the component, not the attribute. [The pwa-auth component styles the component based on the attribute value](https://github.com/pwa-builder/pwa-auth/blob/master/src/pwa-auth.ts#L40). However, when the 'appearance' value is set as a property, it is not reflected to the attribute so the style does not get applied. 

The fix here should be on the `pwa-auth` component to ensure the `appearance` property is [reflected to the attribute](https://lit-element.polymer-project.org/guide/properties#reflected-attributes) or the component is not styled by an attribute value.

ping @JudahGabriel

Here is the issue on the pwa-auth repo: https://github.com/pwa-builder/pwa-auth/issues/9

**Comment by JudahGabriel** [comment]
Thanks for reporting this! (And thanks for the heads-up about reflecting the prop to the attribute, Nikola. 👍

I'll have a fix for this today.

**Comment by JudahGabriel** [comment]
@Odonno, the issue was in pwa-auth itself. That issue has been fixed. We'll deploy a new release of pwa-auth today with the fix.

**Comment by JudahGabriel** [comment]
@Odonno, I've pushed a new release, pwa-auth 0.9.5, with the [fix](https://github.com/pwa-builder/pwa-auth/issues/9) for your issue. 👍
