### ISSUE TITLE
Issue: Not all properties get passed to the web component correctly

### ISSUE THREAD

**Issue by estruyf** [nmetulev/wc-react#5]
Hi @nmetulev I'm using some web components that require boolean values with the wrapper in React. Each time I map these boolean values, none of them are actually passed to the web component. It seems they are just getting ignored.

**Comment by estruyf** [comment]
In the PR I had it fixed, but then I found another issue. 

So the library I'm using is doing styling based on the applied attributes. For instance `<vscode-table bordered />`. In the case of using the wrapper, the property bordered is not applied during the rendering but dynamically added/synced. This causes the issue, as when not present on the element, the styling cannot be applied.

**Comment by nmetulev** [comment]
Closed with #6
